# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e949b0b7bef12fff9307f5a6d5d2a8af0d618f865d08902c598c593d0554e3b40eb402e7af40a2610b6ac0a0df39187eebc8809de6900ae0045e99f8026a557f

test:
  secret_key_base: b38e150a32120e2352c26aeb091bbbd245ac44b4deda89dac455580ce29d49d9fd219b0d551a3380595cbecb6004b5b76abe912f7a8fd14ad47737b00ece22bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
